### PR TITLE
Merge Hephy branch into master as new baseline 

### PR DESCRIPTION
**Pull request by ybuch**
The hephy branch is the most recent branch and includes everything we used for the prelim. analysis during the TB. I propose this branch to be the baseline moving forward.

### CODE REVIEW

**Comment by ybuch** [comment]
@hhanderk What is the difference between initial_masks and applied_masks? Are they re-produced using only files that are available in the git repo so that they can be reliably reproduced? 

@ybuch These folders are identical and include the masks I used for the analysis. Since the masks in applied_masks can be overwritten by the mask script as well as by the corry mask_creator I included this copy.

**Comment by ybuch** [comment]
@hhanderk I would like to reproduce the alignment for the telescope for each of the geoids in a similar fashion to the mask files, so that we have a known baseline with git history and well defined parameters, so that we may compare with the strategy devised by @ajitkmaurya with the millipede module. Are the alignment files you have there produced in that way or should I reproduce them? It is extremely important that we build this analysis on a stable and well understood basis that can be reproduced at any time. 

@ybuch The alignment was done outside the repo, so you would need to run them again to have it in the history. I used the runs 1441, 1477, 1503, 1518, 1544, 1557 and 1564

I think it would be interesting to have Millepede alignments for these 7 runs so that one can compare residuals on the DUT to see what performs better. Ajit: Could you provide the alignmennt files and do the comparison?

**Comment by ybuch** [comment]
@hhanderk I am not too pedantic when it comes to writing commit messages but "added README.md" added a README and an additional 138 files.

**Comment by BenjaminSchwenker** [comment]
Regarding the run_properties.ods file: i think it would be more usefull to upload it as a .csv file to github. than github would show us directly the file content, we can comment on lines and it is easier to open this file in a script.

**Comment by BenjaminSchwenker** [comment]
Before we merge this, someone should try to analysis one or two runs to check if root files are consistent with results obtained during test beams. any volunteer?

**Comment by ajitkmaurya** [comment]
Hi @BenjaminSchwenker, I can try to do that. To do this, I should checkout "hepy" branch?

**Comment by ajitkmaurya** [comment]
Hi @ybuch, I have pushed config files in my branch. 
Files: [align_dut_mpx2.conf](https://github.com/ybuch/corry_config_desytb_2024/blob/IPHC_Strasbourg/align_dut_mpx2.conf)
and 
[align_tel_mpx2.conf](https://github.com/ybuch/corry_config_desytb_2024/blob/IPHC_Strasbourg/align_tel_mpx2.conf)

You can have look at these files.

**Review by BenjaminSchwenker — APPROVED** [review]

**Comment by ajitkmaurya** [comment]
Hi @ybuch, I think we need to change a few things before merging. Here is what I found...

1. Path of the mask files in geo files.
2. Need to modify full_align.sh script. The name of the folder for aligned files is wrong. Name in the script: <<align_geo>>, but there is no folder name <<align_geo>>. In the readme file, the name of the folder is mentioned: <<full_aligned>>
3. In the original script, the corry bin path was defined but in the new script, it is not. I think we need to export (`export PATH=/path/to/corryvreckan/bin`) the corry bin folder (either in the bashrc or at the beginning of the script, or we can just write in the README file about this) 

I am doing an analysis (alignment + analysis) of 2 runs (1441 and 1480). When it finishes then

**Comment by ybuch** [comment]
> Hi @ybuch, I think we need to change a few things before merging. Here is what I found...
> 
>     1. Path of the mask files in geo files.
> 
>     2. Need to modify full_align.sh script. The name of the folder for aligned files is wrong. Name in the script: <<align_geo>>, but there is no folder name <<align_geo>>. In the readme file, the name of the folder is mentioned: <<full_aligned>>
> 
>     3. In the original script, the corry bin path was defined but in the new script, it is not. I think we need to export (`export PATH=/path/to/corryvreckan/bin`) the corry bin folder (either in the bashrc or at the beginning of the script, or we can just write in the README file about this)
> 
> 
> I am doing an analysis (alignment + analysis) of 2 runs (1441 and 1480). When it finishes then

1. This has been fixed in [cbf7773](https://github.com/ybuch/corry_config_desytb_2024/pull/1/commits/cbf77739c6ef4d9a99cbfb64c45f0b346aa75c13)
2. This has been fixed in [255f581](https://github.com/ybuch/corry_config_desytb_2024/pull/1/commits/255f581c3c8dfb0460c7bcabf9cbf516ad1ff847)
3. I believe it is best to have everyone put the corry bin in their respective PATH. I added a comment in 
[390d340](https://github.com/ybuch/corry_config_desytb_2024/pull/1/commits/390d3402114c120eadf481ac792aa66fb1c833a3)

**Review by ajitkmaurya — APPROVED** [review]
From my side, everything looks good.

**Review by hhanderk — APPROVED** [review]

**Review by maxbab1 — APPROVED** [review]

**Pull request merged**
