### PR TITLE
Add analysis scripts

### PR DESCRIPTION
**Pull request by hhanderk**
add the following scripts:

- extract_efficiency.py: extract efficiencies from log files
- extract_root_files.py: extract ToT, Cluster size, Spatial Residuals from root files
- mask_calculator.py: extracts information about masked pixels from mask files

### CODE REVIEW

**Comment by hhanderk** [comment]
Started from HEPHY branch

**Comment by BenjaminSchwenker** [comment]
We should first merge pr 1 and than this one. 
@hhanderk : could you review, comment, approve pr 1?

**Comment by BenjaminSchwenker** [comment]
Thanks a lot for your effort @hhanderk . 

My initial idea was to ask people to only upload the output root files from corry back to the cloud. Now this seems to imply some information loss as we cannot than automatically extract efficiency numbers and masked pixel numbers from the 
data uploaded to the cloud. 

I think this is a must: the data uploaded to the cloud should should be fully sufficient to reproduce all result numbers. 

Should we change the plan to also ask people to upload some of the log files as well to the cloud?

**Comment by ybuch** [comment]
@hhanderk Could you change the extract_root file to also read out the efficiency from a TEfficiency Graph in the root files? An example for this is at the bottom of the file i sent you. It would allow us to unify everything in one script and we would only need the .root file as data source instead of the root+log file.

**Comment by hhanderk** [comment]
> @hhanderk Could you change the extract_root file to also read out the efficiency from a TEfficiency Graph in the root files? An example for this is at the bottom of the file i sent you. It would allow us to unify everything in one script and we would only need the .root file as data source instead of the root+log file.

@ybuch I definitely agree, however I faced some issues with importing ROOT to python which is the reason I wrote a separate script.

**Comment by ybuch** [comment]
@ajitkmaurya I like your script. It can easily appended to extract a couple of other values and it uses ROOT directly. I would change it to export to csv by writing it all into a pandas frame and using that to export to csv.

**Comment by ajitkmaurya** [comment]
Hi @ybuch, Thanks.  I wanted to extract more information like the mean and sigma of all telescope planes, average track chi2/ndf, average track multiplicity, average cluster size for DUT, etc.

**Comment by ybuch** [comment]
I am currently working on it. Give me a minute :D

**Comment by ybuch** [comment]
@ajitkmaurya add new values by adding it into the dict with row_dict.update({'name':val}) and add column name in "columns" list during the dataframe creation.

**Comment by ybuch** [comment]
I dont know if you want to keep the text output and console print out. If not you can delete when adding your values :D

**Comment by ybuch** [comment]
@ajitkmaurya Cluster charge, seed charge, cluster sizes were requested by Benjamin

**Comment by ajitkmaurya** [comment]
Yes, thanks. I am trying to do `git pull` for your latest commit. but somehow not working. 
Do we want to extract average value for `Cluster charge, seed charge, cluster sizes ` ?

**Comment by ybuch** [comment]
Sounds good
Did the git pull work now?

**Comment by ajitkmaurya** [comment]
Now it worked. Let me add other variables in the list.

**Comment by BenjaminSchwenker** [comment]
I am confused that still 650 files would be changed on master when this is merged. could you try perform a 'git pull master' on this branch ....

**Comment by ybuch** [comment]
@ajitkmaurya I would like to converge on this matter and merge the branch. You mentioned that you want to add other variables. If that is still the case I will leave the pr open. Also I propose to quickly rename the script, as it is slated to extract more than just the efficiencies and residuals and even than it also performs fits and so on. Maybe extract_analysis

**Comment by ajitkmaurya** [comment]
@ybuch, I am still not finished adding other variables in the script. I will try to add it by today and if not then for sure tomorrow.

**Comment by ybuch** [comment]
@ajitkmaurya  Thank you :D I didnt want to stress you

**Comment by ybuch** [comment]
@ajitkmaurya I will quickly finish this up by adding residuals for the telescope planes and adding simple cluster properties and merge directly after so we have it in main and can use it. We can do another pr to expand on that later

**Comment by ajitkmaurya** [comment]
@ybuch, really sorry for the delay due to some unavoidable reason. Yes, I agree with you and thank you for doing it.

**Pull request merged**
