### PR TITLE
5 add run information of runs pre 1400

### LINKED ISSUE #5: Add run information of runs pre 1400

### PR DESCRIPTION
**Pull request by ybuch**

### CODE REVIEW

**Comment by ybuch** [comment]
@ajitkmaurya I have added (among other things) the material budget to the initial geo files

**Comment by ybuch** [comment]
I am aligning geoID1 now. If it works and the run 1382 can be analyzed with corry I will merge this into master and create a new minor version

**Comment by ajitkmaurya** [comment]
Thanks @ybuch, I think the AlignmentTrackChi2 method will take some time to finish.

**Comment by ybuch** [comment]
Geo id was aligned and the analysis looks very good

**Pull request merged**
